version: '3.4'

services:
  app:
    image: vedant2040/todolist
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - todolist.db:/app/db
volumes:
  todolist.db:
